from pathlib import Path
import argparse
from ancyr_tools.symbol_parser import parse_symbol_file
from ancyr_tools.ids_collection_logs import IdsCollectionSample
from ancyr_tools.operation_id_map import write_operation_id_map


def cmdline():
    parser = argparse.ArgumentParser(
        prog='ancyr-gen-op-id-map-from-logs',
        description='Generate an operation ID map from the provided IDS logs and Symbol table')
    parser.add_argument("output_file", type=Path, help="Destination file")
    parser.add_argument("symbol_file", type=Path, help="The symbol file generated by the compiler")
    parser.add_argument("log_file", type=Path, help="The IDS logs generated by ancyr-agent")

    args = parser.parse_args()

    symbols_by_offset, symbols_by_name = parse_symbol_file(args.symbol_file)
    ids_samples = IdsCollectionSample.load_ids_collection_log(args.log_file)
    function_names = IdsCollectionSample.get_function_names(ids_samples, symbols_by_offset)
    unique_symbols = {}
    for f in function_names:
        if f not in unique_symbols:
            unique_symbols[f] = symbols_by_name[f]
    write_operation_id_map(args.output_file, unique_symbols)

if __name__ == "__main__":
    cmdline()